spring:
  profile.active: dev
---
spring:
  profiles: dev
urls:
  products: https://api.mercadolibre.com/items?ids=
  
---
spring:
  profiles: prod
urls:  
  products: https://api.mercadolibre.com/items?ids=